### ISSUE TITLE
Fix CSS imports when using tailwind rails and propshaft

### ISSUE THREAD

**Issue by afomera** [afomera/richer_text#18]

**Comment by stephenson** [comment]
Is this related to the error I am getting on a fresh install? 

` Error: Failed to find 'highlight.js/styles/github-dark.css'
13:25:32 css.1  |   in [
13:25:32 css.1  |     /Users/niklas/work/kursus/app/assets/stylesheets
13:25:32 css.1  |   ]
13:25:32 css.1  |     at /snapshot/tailwindcss/node_modules/postcss-import/lib/resolve-id.js:35:13
13:25:32 css.1  |     at async LazyResult.runAsync (/snapshot/tailwindcss/node_modules/postcss/lib/lazy-result.js:261:11)
13:25:32 css.1  |     at async Object.watch (/snapshot/tailwindcss/lib/cli/build/plugin.js:370:13)
13:25:32 css.1  |     at async build (/snapshot/tailwindcss/lib/cli/build/index.js:47:9)
`

**Comment by bruno-costanzo** [comment]
I'm having the same issue. I can try to fix it but I really don't know where to start.

**Comment by adenta** [comment]
Would this be resolved by prefixing tailwind classes when like tf-?
